### ISSUE TITLE
WORKING LIST OF THE ADDITIONAL SWIFTUI LIBRARIES

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#1017]
Active list of all available views and modifiers we will wrap from additional SwiftUI libraries:

<h1>VIEWS</h1>

- [ ] Authentication services views liveview-native/liveview-native-swiftui-authentication-services/issues/1
- [x] AVKit views liveview-native/liveview-native-swiftui-avkit/issues/5
- [ ] CoreLocationUI views liveview-native/liveview-native-swiftui-corelocationui/issues/1
- [ ] Device Activity views liveview-native/liveview-native-swiftui-deviceactivity/issues/1
- ~~HomeKit views liveview-native/liveview-native-swiftui-homekit/issues/1~~ WILL NOT SUPPORT
- [ ] MapKit views liveview-native/liveview-native-swiftui-mapkit/issues/2
- ~~MusicKit views liveview-native/liveview-native-swiftui-musickit/issues/1~~ WILL NOT SUPPORT
- [x] Swift Charts views liveview-native/liveview-native-swiftui-charts/issues/91
- [ ] PassKit views liveview-native/liveview-native-swiftui-passkit/issues/2
- [ ] PhotoKit views liveview-native/liveview-native-swiftui-photokit/issues/2

<h1>MODIFIERS</h1>

- ~~Authentication services modifiers liveview-native/liveview-native-swiftui-authentication-services/issues/5~~ WILL NOT SUPPORT
- [ ] AVKit modifiers liveview-native/liveview-native-swiftui-avkit/issues/3
- [ ] MapKit modifiers liveview-native/liveview-native-swiftui-mapkit/issues/30
- [ ] Swift Charts modifiers liveview-native/liveview-native-swiftui-charts/issues/90
