### ISSUE TITLE
SCOPING: WORKING LIST OF BINDINGS FOR SWIFTUI

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#1095]
Active list of all available bindings we can map. From:

[List of Bindings](https://github.com/liveview-native/liveview-client-swiftui/issues/159)

<h1>LIVEVIEW BINDINGS FOR SWIFTUI</h1>

<h2>Click Events</h2>

- [x] `phx-click` liveview-native/liveview-client-swiftui#1096 

<h2>Focus Events</h2>

- [x] `phx-blur` liveview-native/liveview-client-swiftui#1097 
- [x] `phx-focus` liveview-native/liveview-client-swiftui#1098 
- [x] `phx-window-blur` liveview-native/liveview-client-swiftui#1099 
- [x] `phx-window-focus` liveview-native/liveview-client-swiftui#1100 

<h2>Key Events</h2>

- [ ] `phx-keydown` liveview-native/liveview-client-swiftui#1101 
- [ ] `phx-window-keydown` liveview-native/liveview-client-swiftui#1102

**Comment by BrooklinJazz** [comment]
Posting for my own attention: this work may require an update to the "event-bindings" guide when merged.
