### ISSUE TITLE
Documentation: Working list of SwiftUI views

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#336]
As a PO I would like to have the documentation for the [Working list of SwiftUI views](https://github.com/liveviewnative/liveview-client-swiftui/issues/42)

SwiftUI:
- User Interface Element
    - Text input and output
        - [x] [Text](https://developer.apple.com/documentation/swiftui/text) liveviewnative/liveview-client-swiftui#337
        - [x] [Label](https://developer.apple.com/documentation/swiftui/label) liveviewnative/liveview-client-swiftui#350
        - [x] [TextField](https://developer.apple.com/documentation/swiftui/textfield) liveviewnative/liveview-client-swiftui#351
        - [x] [SecureField](https://developer.apple.com/documentation/swiftui/securefield) liveviewnative/liveview-client-swiftui#352
        - [x] [TextEditor](https://developer.apple.com/documentation/swiftui/texteditor) liveviewnative/liveview-client-swiftui#353 
    - Images
        - [x] [Image](https://developer.apple.com/documentation/swiftui/image) liveviewnative/liveview-client-swiftui#338
        - [x] [AsyncImage](https://developer.apple.com/documentation/swiftui/asyncimage) liveviewnative/liveview-client-swiftui#339
    - Controls and indicator
        - Buttons
            - [x] [Button](https://developer.apple.com/documentation/swiftui/button) liveviewnative/liveview-client-swiftui#340  
            - [x] [EditButton](https://developer.apple.com/documentation/swiftui/editbutton) liveviewnative/liveview-client-swiftui#354
            - [x] [PasteButton](https://developer.apple.com/documentation/swiftui/pastebutton) liveviewnative/liveview-client-swiftui#355
            - [x] [RenameButton](https://developer.apple.com/documentation/swiftui/renamebutton) liveviewnative/liveview-client-swiftui#356
        - Links
            - [x] [Link](https://developer.apple.com/documentation/swiftui/link) liveviewnative/liveview-client-swiftui#357
            - [x] [ShareLink](https://developer.apple.com/documentation/swiftui/sharelink) liveviewnative/liveview-client-swiftui#358
            - [x] [TextFieldLink](https://developer.apple.com/documentation/swiftui/textfieldlink) liveviewnative/liveview-client-swiftui#359
        - Menus
            - [x] [Menu](https://developer.apple.com/documentation/swiftui/menu) liveviewnative/liveview-client-swiftui#360 
        - Value inputs
            - [x] [Slider](https://developer.apple.com/documentation/swiftui/slider) liveviewnative/liveview-client-swiftui#361
            - [x] [Stepper](https://developer.apple.com/documentation/swiftui/stepper) liveviewnative/liveview-client-swiftui#362
            - [x] [Toggle](https://developer.apple.com/documentation/swiftui/toggle) liveviewnative/liveview-client-swiftui#363
        - Pickers
            - [x] [Picker](https://developer.apple.com/documentation/swiftui/picker) liveviewnative/liveview-client-swiftui#364
            - [x] [DatePicker](https://developer.apple.com/documentation/swiftui/datepicker) liveviewnative/liveview-client-swiftui#365
            - [x] [MultiDatePicker](https://developer.apple.com/documentation/swiftui/multidatepicker) liveviewnative/liveview-client-swiftui#366
            - [x] [ColorPicker](https://developer.apple.com/documentation/swiftui/colorpicker) liveviewnative/liveview-client-swiftui#367
        - Indicators
            - [x] [Gauge](https://developer.apple.com/documentation/swiftui/gauge) liveviewnative/liveview-client-swiftui#368
            - [x] [ProgressView](https://developer.apple.com/documentation/swiftui/progressview) liveviewnative/liveview-client-swiftui#369
            - ~~[DefaultDateProgressLabel](https://developer.apple.com/documentation/swiftui/defaultdateprogresslabel) liveviewnative/liveview-client-swiftui#341~~ **PART OF liveviewnative/liveview-client-swiftui#369**
    - Shapes
        - [x] [Rectangle](https://developer.apple.com/documentation/swiftui/rectangle) liveviewnative/liveview-client-swiftui#342
        - [x] [RoundedRectangle](https://developer.apple.com/documentation/swiftui/roundedrectangle) liveviewnative/liveview-client-swiftui#343
        - [x] [Circle](https://developer.apple.com/documentation/swiftui/circle) liveviewnative/liveview-client-swiftui#370
        - [x] [Ellipse](https://developer.apple.com/documentation/swiftui/ellipse) liveviewnative/liveview-client-swiftui#371
        - [x] [Capsule](https://developer.apple.com/documentation/swiftui/capsule) liveviewnative/liveview-client-swiftui#372
        - [x] [ContainerRelativeShape](https://developer.apple.com/documentation/swiftui/containerrelativeshape) liveviewnative/liveview-client-swiftui#373
    - Drawing and graphics
        - [x] [Color](https://developer.apple.com/documentation/swiftui/color) liveviewnative/liveview-client-swiftui#400
- Layout containers
    - Stacks
        - [x] [HStack](https://developer.apple.com/documentation/swiftui/hstack) liveviewnative/liveview-client-swiftui#344
        - [x] [VStack](https://developer.apple.com/documentation/swiftui/vstack) liveviewnative/liveview-client-swiftui#345
        - [x] [ZStack](https://developer.apple.com/documentation/swiftui/zstack) liveviewnative/liveview-client-swiftui#346
    - Lazy stacks
        - [x] [LazyHStack](https://developer.apple.com/documentation/swiftui/lazyhstack) liveviewnative/liveview-client-swiftui#374
        - [x] [LazyVStack](https://developer.apple.com/documentation/swiftui/lazyvstack) liveviewnative/liveview-client-swiftui#375 
    - Grids
        - [x] [Grid](https://developer.apple.com/documentation/swiftui/grid) liveviewnative/liveview-client-swiftui#376
        - [x] [GridRow](https://developer.apple.com/documentation/swiftui/gridrow) liveviewnative/liveview-client-swiftui#377
    - Lazy grids
        - [x] [LazyHGrid](https://developer.apple.com/documentation/swiftui/lazyhgrid) liveviewnative/liveview-client-swiftui#378 
        - [x] [LazyVGrid](https://developer.apple.com/documentation/swiftui/lazyvgrid) liveviewnative/liveview-client-swiftui#379 
        - [x] [GridItem](https://developer.apple.com/documentation/swiftui/griditem) liveviewnative/liveview-client-swiftui#380
    - Separators
        - [x] [Spacer](https://developer.apple.com/documentation/swiftui/spacer) liveviewnative/liveview-client-swiftui#347
        - [x] [Divider](https://developer.apple.com/documentation/swiftui/divider) liveviewnative/liveview-client-swiftui#381
    - Layout transitions
        - [ ] [AnyLayout](https://developer.apple.com/documentation/swiftui/anylayout) liveviewnative/liveview-client-swiftui#402
        - [ ] [HStackLayout](https://developer.apple.com/documentation/swiftui/hstacklayout) liveviewnative/liveview-client-swiftui#403
        - [ ] [VStackLayout](https://developer.apple.com/documentation/swiftui/vstacklayout) liveviewnative/liveview-client-swiftui#404
        - [ ] [ZStackLayout](https://developer.apple.com/documentation/swiftui/zstacklayout) liveviewnative/liveview-client-swiftui#405
        - [ ] [GridLayout](https://developer.apple.com/documentation/swiftui/gridlayout) liveviewnative/liveview-client-swiftui#406
    - Sizing, spacing, and orientation
        - [x] [ViewThatFits](https://developer.apple.com/documentation/swiftui/viewthatfits) liveviewnative/liveview-client-swiftui#382
    - Collection containers
        - [x] [List](https://developer.apple.com/documentation/swiftui/list) liveviewnative/liveview-client-swiftui#383
        - [x] [Section](https://developer.apple.com/documentation/swiftui/section) liveviewnative/liveview-client-swiftui#384
        - [x] [Tables](https://developer.apple.com/documentation/swiftui/tables) liveviewnative/liveview-client-swiftui#385
        - [x] [TableColumn](https://developer.apple.com/documentation/swiftui/tablecolumn) liveviewnative/liveview-client-swiftui#386
        - [x] [TableRow](https://developer.apple.com/documentation/swiftui/tablerow) liveviewnative/liveview-client-swiftui#387
    - Forms
        - [x] [Form](https://developer.apple.com/documentation/swiftui/form) liveviewnative/liveview-client-swiftui#388
        - [x] [LabeledContent](https://developer.apple.com/documentation/swiftui/labeledcontent) liveviewnative/liveview-client-swiftui#390
    - Groups
        - [x] [Group](https://developer.apple.com/documentation/swiftui/group) liveviewnative/liveview-client-swiftui#391
        - [x] [GroupBox](https://developer.apple.com/documentation/swiftui/groupbox) liveviewnative/liveview-client-swiftui#392
        - [x] [ControlGroup](https://developer.apple.com/documentation/swiftui/controlgroup) liveviewnative/liveview-client-swiftui#393
    - Scroll views
        - [x] [ScrollView](https://developer.apple.com/documentation/swiftui/scrollview) liveviewnative/liveview-client-swiftui#348
        - ~~[ScrollViewReader](https://developer.apple.com/documentation/swiftui/scrollviewreader) liveviewnative/liveview-client-swiftui#394~~**PART OF liveviewnative/liveview-client-swiftui#348**
    - Presentation containers
        - [x] [NavigationStack](https://developer.apple.com/documentation/swiftui/navigationstack) liveviewnative/liveview-client-swiftui#395
        - [x] [NavigationSplitView](https://developer.apple.com/documentation/swiftui/navigationsplitview) liveviewnative/liveview-client-swiftui#396
        - [x] [NavigationLink](https://developer.apple.com/documentation/swiftui/navigationlink) liveviewnative/liveview-client-swiftui#349
        - [x] [TabView](https://developer.apple.com/documentation/swiftui/tabview) liveviewnative/liveview-client-swiftui#397
        - [x] [HSplitView](https://developer.apple.com/documentation/swiftui/hsplitview) liveviewnative/liveview-client-swiftui#398
        - [x] [VSplitView](https://developer.apple.com/documentation/swiftui/vsplitview) liveviewnative/liveview-client-swiftui#399
    - Lists
        - [x] [ DisclosureGroup](https://developer.apple.com/documentation/swiftui/disclosuregroup) liveviewnative/liveview-client-swiftui#401

**Comment by AZholtkevych** [comment]
FYI @bcardarella @carson-katri @shadowfacts
