### ISSUE TITLE
Scoping: Working list of SwiftUI views

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#42]
Active list of all available views we will wrap. From:
- https://developer.apple.com/documentation/swiftui

Discussion on how and if a particular view will be implemented should happen within the associated issue not in this issue.

SwiftUI:
- User Interface Element
    - Text input and output
        - [x] [Text](https://developer.apple.com/documentation/swiftui/text) liveviewnative/liveview-client-swiftui#43
        - [x] [Label](https://developer.apple.com/documentation/swiftui/label) liveviewnative/liveview-client-swiftui#44 
        - [x] [TextField](https://developer.apple.com/documentation/swiftui/textfield) liveviewnative/liveview-client-swiftui#45
        - [x] [SecureField](https://developer.apple.com/documentation/swiftui/securefield) liveviewnative/liveview-client-swiftui#46
        - [x] [TextEditor](https://developer.apple.com/documentation/swiftui/texteditor) liveviewnative/liveview-client-swiftui#47 
    - Images
        - [x] [Image](https://developer.apple.com/documentation/swiftui/image) liveviewnative/liveview-client-swiftui#48
        - [x] [AsyncImage](https://developer.apple.com/documentation/swiftui/asyncimage) liveviewnative/liveview-client-swiftui#49
    - Controls and indicator
        - Buttons
            - [x] [Button](https://developer.apple.com/documentation/swiftui/button) liveviewnative/liveview-client-swiftui#60  
            - [x] [EditButton](https://developer.apple.com/documentation/swiftui/editbutton) liveviewnative/liveview-client-swiftui#61
            - [x] [PasteButton](https://developer.apple.com/documentation/swiftui/pastebutton) liveviewnative/liveview-client-swiftui#62
            - [x] [RenameButton](https://developer.apple.com/documentation/swiftui/renamebutton) liveviewnative/liveview-client-swiftui#63
        - Links
            - [x] [Link](https://developer.apple.com/documentation/swiftui/link) liveviewnative/liveview-client-swiftui#64
            - [x] [ShareLink](https://developer.apple.com/documentation/swiftui/sharelink) liveviewnative/liveview-client-swiftui#65
            - [x] [TextFieldLink](https://developer.apple.com/documentation/swiftui/textfieldlink) liveviewnative/liveview-client-swiftui#66
        - Menus
            - [x] [Menu](https://developer.apple.com/documentation/swiftui/menu) liveviewnative/liveview-client-swiftui#67 
            - ~~[MenuOrder](https://developer.apple.com/documentation/swiftui/menuorder) liveviewnative/liveview-client-swiftui#68~~ **WILL NOT SUPPORT**
        - Value inputs
            - [x] [Slider](https://developer.apple.com/documentation/swiftui/slider) liveviewnative/liveview-client-swiftui#69
            - [x] [Stepper](https://developer.apple.com/documentation/swiftui/stepper) liveviewnative/liveview-client-swiftui#70
            - [x] [Toggle](https://developer.apple.com/documentation/swiftui/toggle) liveviewnative/liveview-client-swiftui#71 
        - Pickers
            - [x] [Picker](https://developer.apple.com/documentation/swiftui/picker) liveviewnative/liveview-client-swiftui#72
            - [x] [DatePicker](https://developer.apple.com/documentation/swiftui/datepicker) liveviewnative/liveview-client-swiftui#73
            - [x] [MultiDatePicker](https://developer.apple.com/documentation/swiftui/multidatepicker) liveviewnative/liveview-client-swiftui#74
            - [x] [ColorPicker](https://developer.apple.com/documentation/swiftui/colorpicker) liveviewnative/liveview-client-swiftui#75
        - Indicators
            - [x] [Gauge](https://developer.apple.com/documentation/swiftui/gauge) liveviewnative/liveview-client-swiftui#76
            - [x] [ProgressView](https://developer.apple.com/documentation/swiftui/progressview) liveviewnative/liveview-client-swiftui#77
            - ~~[DefaultDateProgressLabel](https://developer.apple.com/documentation/swiftui/defaultdateprogresslabel) liveviewnative/liveview-client-swiftui#78~~ **PART OF liveviewnative/liveview-client-swiftui#77**
    - Shapes
        - ~~[AnyShape](https://developer.apple.com/documentation/swiftui/anyshape) liveviewnative/liveview-client-swiftui#79~~ **WILL NOT SUPPORT**
        - [x] [Rectangle](https://developer.apple.com/documentation/swiftui/rectangle) liveviewnative/liveview-client-swiftui#80
        - [x] [RoundedRectangle](https://developer.apple.com/documentation/swiftui/roundedrectangle) liveviewnative/liveview-client-swiftui#81
        - [x] [Circle](https://developer.apple.com/documentation/swiftui/circle) liveviewnative/liveview-client-swiftui#82
        - [x] [Ellipse](https://developer.apple.com/documentation/swiftui/ellipse) liveviewnative/liveview-client-swiftui#83
        - [x] [Capsule](https://developer.apple.com/documentation/swiftui/capsule) liveviewnative/liveview-client-swiftui#84
        -  ~~[Path](https://developer.apple.com/documentation/swiftui/path) liveviewnative/liveview-client-swiftui#85~~ **WILL NOT SUPPORT**
        -  ~~[ScaledShape](https://developer.apple.com/documentation/swiftui/scaledshape) liveviewnative/liveview-client-swiftui#86~~ **WILL NOT SUPPORT**
        - ~~[RotatedShape](https://developer.apple.com/documentation/swiftui/rotatedshape) liveviewnative/liveview-client-swiftui#87~~ **WILL NOT SUPPORT**
        - ~~[OffsetShape](https://developer.apple.com/documentation/swiftui/offsetshape) liveviewnative/liveview-client-swiftui#88~~ **WILL NOT SUPPORT**
        - ~~[TransformedShape](https://developer.apple.com/documentation/swiftui/transformedshape) liveviewnative/liveview-client-swiftui#89~~ **WILL NOT SUPPORT**
        - [x] [ContainerRelativeShape](https://developer.apple.com/documentation/swiftui/containerrelativeshape) liveviewnative/liveview-client-swiftui#90
    - Drawing and graphics
        - ~~[Canvas](https://developer.apple.com/documentation/swiftui/canvas) liveviewnative/liveview-client-swiftui#91~~ **WILL NOT SUPPORT**
        - [x] [Color](https://developer.apple.com/documentation/swiftui/color) liveviewnative/liveview-client-swiftui#204
- Layout containers
    - Stacks
        - [x] [HStack](https://developer.apple.com/documentation/swiftui/hstack) liveviewnative/liveview-client-swiftui#92 
        - [x] [VStack](https://developer.apple.com/documentation/swiftui/vstack) liveviewnative/liveview-client-swiftui#93
        - [x] [ZStack](https://developer.apple.com/documentation/swiftui/zstack) liveviewnative/liveview-client-swiftui#94 
    - Lazy stacks
        - [x] [LazyHStack](https://developer.apple.com/documentation/swiftui/lazyhstack) liveviewnative/liveview-client-swiftui#95
        - [x] [LazyVStack](https://developer.apple.com/documentation/swiftui/lazyvstack) liveviewnative/liveview-client-swiftui#96 
    - Grids
        - [x] [Grid](https://developer.apple.com/documentation/swiftui/grid) liveviewnative/liveview-client-swiftui#97 
        - [x] [GridRow](https://developer.apple.com/documentation/swiftui/gridrow) liveviewnative/liveview-client-swiftui#98 
    - Lazy grids
        - [x] [LazyHGrid](https://developer.apple.com/documentation/swiftui/lazyhgrid) liveviewnative/liveview-client-swiftui#99 
        - [x] [LazyVGrid](https://developer.apple.com/documentation/swiftui/lazyvgrid) liveviewnative/liveview-client-swiftui#100 
        - [x] [GridItem](https://developer.apple.com/documentation/swiftui/griditem) liveviewnative/liveview-client-swiftui#101 
    - Separators
        - [x] [Spacer](https://developer.apple.com/documentation/swiftui/spacer) liveviewnative/liveview-client-swiftui#102 
        - [x] [Divider](https://developer.apple.com/documentation/swiftui/divider) liveviewnative/liveview-client-swiftui#103 
    - Layout transitions
        - [ ] [AnyLayout](https://developer.apple.com/documentation/swiftui/anylayout) liveviewnative/liveview-client-swiftui#104
        - [ ] [HStackLayout](https://developer.apple.com/documentation/swiftui/hstacklayout) liveviewnative/liveview-client-swiftui#105
        - [ ] [VStackLayout](https://developer.apple.com/documentation/swiftui/vstacklayout) liveviewnative/liveview-client-swiftui#106
        - [ ] [ZStackLayout](https://developer.apple.com/documentation/swiftui/zstacklayout) liveviewnative/liveview-client-swiftui#107
        - [ ] [GridLayout](https://developer.apple.com/documentation/swiftui/gridlayout) liveviewnative/liveview-client-swiftui#108
    - Sizing, spacing, and orientation
        - [x] [ViewThatFits](https://developer.apple.com/documentation/swiftui/viewthatfits) liveviewnative/liveview-client-swiftui#109 
    - Collection containers
        - [x] [List](https://developer.apple.com/documentation/swiftui/list) liveviewnative/liveview-client-swiftui#110
        - [x] [Section](https://developer.apple.com/documentation/swiftui/section) liveviewnative/liveview-client-swiftui#111
        - [x] [Tables](https://developer.apple.com/documentation/swiftui/tables) liveviewnative/liveview-client-swiftui#112
        - [x] [TableColumn](https://developer.apple.com/documentation/swiftui/tablecolumn) liveviewnative/liveview-client-swiftui#113
        - [x] [TableRow](https://developer.apple.com/documentation/swiftui/tablerow) liveviewnative/liveview-client-swiftui#114
    - Forms
        - [x] [Form](https://developer.apple.com/documentation/swiftui/form) liveviewnative/liveview-client-swiftui#115
        - [x] [LabeledContent](https://developer.apple.com/documentation/swiftui/labeledcontent) liveviewnative/liveview-client-swiftui#116
    - Groups
        - [x] [Group](https://developer.apple.com/documentation/swiftui/group) liveviewnative/liveview-client-swiftui#117
        - [x] [GroupBox](https://developer.apple.com/documentation/swiftui/groupbox) liveviewnative/liveview-client-swiftui#118
        - [x] [ControlGroup](https://developer.apple.com/documentation/swiftui/controlgroup) liveviewnative/liveview-client-swiftui#119
    - Scroll views
        - [x] [ScrollView](https://developer.apple.com/documentation/swiftui/scrollview) liveviewnative/liveview-client-swiftui#120
        - [x] [ScrollViewReader](https://developer.apple.com/documentation/swiftui/scrollviewreader) liveviewnative/liveview-client-swiftui#121
    - Presentation containers
        - [x] [NavigationStack](https://developer.apple.com/documentation/swiftui/navigationstack) liveviewnative/liveview-client-swiftui#122 
        - [x] [NavigationSplitView](https://developer.apple.com/documentation/swiftui/navigationsplitview) liveviewnative/liveview-client-swiftui#123
        - [x] [NavigationLink](https://developer.apple.com/documentation/swiftui/navigationlink) liveviewnative/liveview-client-swiftui#124
        - [x] [TabView](https://developer.apple.com/documentation/swiftui/tabview) liveviewnative/liveview-client-swiftui#125
        - [x] [HSplitView](https://developer.apple.com/documentation/swiftui/hsplitview) liveviewnative/liveview-client-swiftui#126
        - [x] [VSplitView](https://developer.apple.com/documentation/swiftui/vsplitview) liveviewnative/liveview-client-swiftui#127
        - ~~[TimelineView](https://developer.apple.com/documentation/swiftui/timelineview) liveviewnative/liveview-client-swiftui#128~~ **WILL NOT SUPPORT**
    - Lists
        - ~~[OutlineGroup](https://developer.apple.com/documentation/swiftui/outlinegroup) liveviewnative/liveview-client-swiftui#205~~ **WILL NOT SUPPORT**
        - [x] [ DisclosureGroup](https://developer.apple.com/documentation/swiftui/disclosuregroup) liveviewnative/liveview-client-swiftui#206

**Comment by bcardarella** [comment]
@AZholtkevych please make shire this check list is being updated as issues are being closed

**Comment by lcr0815** [comment]
don't know crap about SwuitUI but would definitely like to get involved somehow. I'm interested  in all related items with Elixir/Phoenix/LiveVew...

**Comment by bcardarella** [comment]
@lcr0815 there is a bunch of Elixir related work too if that is something you'd want to take a look at :)

**Comment by bcardarella** [comment]
@AZholtkevych can we remove the recently added scope into separate issues that are specific to those libs? I'd like to keep this one just for SwiftUI

**Comment by AZholtkevych** [comment]
Will do, @bcardarella

**Comment by AZholtkevych** [comment]
Done, @bcardarella
