### ISSUE TITLE
SCOPING: WORKING LIST OF SWIFTUI UPDATED MODIFIERS

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#979]
Active list of primary modifiers for the Swift Chart:
- https://developer.apple.com/documentation/updates/swiftui

Discussion on how and if a particular view will be implemented should happen within the associated issue not in this issue.

<h1>SWIFTUI UPDATED MODIFIERS</h1>

<h2>Toolbars</h2>

- [ ] ornament(visibility:attachmentAnchor:contentAlignment:ornament:) [BETA] #1037 
- [x] toolbarTitleDisplayMode(_:) [BETA] #1050 

<h2>Drawing and Graphics</h2>

- [ ] visualEffect3D(_:) [BETA] #1038 
- [ ] rotation3DEffect(_⚓) [BETA] #1039 
- [ ] scaleEffect(x:y:z⚓) #1040 
- ~~visualEffect(_:) [BETA] #1077~~ WILL NOT SUPPORT

<h2>View configuration</h2>

- [ ] glassBackgroundEffect(displayMode:) [BETA] #1041 
- [ ] preferredSurroundingsEffect(_:) [BETA] #1042 

<h2>Layout adjustments</h2>

- [ ] offset(z:) [BETA] #1043 
- [ ] padding3D(_:) [BETA] #1044 
- [ ] frame(depth:alignment:) [BETA] #1045
- [ ] safeAreaPadding(_:) [BETA] #1088 
- [ ] contentMargins(_:_:for:) [BETA] #1089 

<h2>Navigation</h2>

- ~~navigationDestination(item:destination:) [BETA] #1046~~ WILL NOT SUPPORT

<h2>Modal presentations</h2>

- [ ] fileExporter(isPresented:document:contentTypes:defaultFilename:onCompletion:onCancellation:) [BETA] #1047 
- [ ] dialogSeverity(_:) #1048 
- [ ] dialogIcon(_:) #1049 
- [x] inspector(isPresented:content:) [BETA] #1070 

<h2>Search</h2>

- [x] searchable(text:isPresented:placement:prompt:) [BETA] #1051 
- [x] searchable(text:editableTokens:isPresented:placement:prompt:token:) [BETA] #1052 

<h2>Animations</h2>

- [ ] withAnimation(_:completionCriteria:_:completion:) [BETA] #1071 

<h2>Text input and output</h2>

- [ ] typesettingLanguage(_:isEnabled:) [BETA] #1072 
- [x] textScale(_:isEnabled:) [BETA] #1073 

<h2>Shapes</h2>

- [x] fill(_:style:) [BETA] #1074 
- [x] stroke(_:style:antialiased:) [BETA] #1075 

<h2>View fundamentals</h2>

<h3>View</h3>

<h4>Appearance modifiers</h4>

- [ ] allowedDynamicRange(_:) [BETA] #1076 

<h2>Layout fundamentals</h2>

- [ ] containerBackground(_:for:) [BETA] #1078 

<h2>Lists</h2>

- [x] selectionDisabled(_:) [BETA] #1079 
- [x] listRowSpacing(_:) #1080 
- [x] listSectionSpacing(_:) [BETA] #1081 
- [ ] badgeProminence(_:) [BETA] #1082 
- [ ] alternatingRowBackgrounds(_:) [BETA] #1083 

<h2>Tables</h2>

- [ ] tableColumnHeaders(_:) [BETA] #1084 

<h2>Scroll views</h2>

- [x] scrollIndicatorsFlash(onAppear:) [BETA] #1085 
- [x] scrollClipDisabled(_:) [BETA] #1086 
- [x] scrollTargetBehavior(_:) [BETA] #1087 
- [ ] scrollTransition(_:axis:transition:) [BETA] #1090 

<h2>Input events</h2>

- [ ] onKeyPress(_:action:) [BETA] #1091 

<h2>Controls and indicators</h2>

- [ ] sensoryFeedback(_:trigger:) [BETA] #1092 

<h2>Focus</h2>

- [x] focusable(_:interactions:) [BETA] #1093 
- [x] focusEffectDisabled(_:) [BETA] #1094
